spring:
  application:
    name: auth
  devtools:
    livereload:
      enabled: true
  messages:
    basename: /messages
    encoding: UTF-8
  jwt:
    secretKey: testSecret
    tokenValidMinutes: 360
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:30432/auth
    username: ENC(87N1B0jWzzNM0Y5NiUjmgyLTzoQGWeEr)
    password: ENC(32mylwDjuYN9IizAN1RoXVNNtnBpfrA0)
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 30
  sql:
    init:
      mode: always
      continue-on-error: false
      platform: postgresql
      data-locations: classpath:data-postgres.sql

# server
server:
  title: spring-micro-auth
  version: '@project.version@'
  port: 8080

# documentation
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# logging
logging:
  file:
    name: logs/auth.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/auth-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 1GB
      max-history: 7
      clean-history-on-start: false
  level:
      org:
        springframework:
          security: INFO
      io:
        coolexplorer: DEBUG